version: "3"

dotenv: ['.env']

tasks:
  validate_lint:
    cmds:
      - poetry run black --check --preview .
      - poetry run flake8 .
      - poetry run isort -c --df .

  run_tests:
    cmds:
      - poetry run pytest ./acetube_streamlit/tests

  run_docker:
    cmds:
      - docker run -it --rm -p 8501:8501 --env GITHUB_TOKEN=$GITHUB_TOKEN acetube_streamlit
